# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/enchilada/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),enchilada)

$(call add-radio-file-sha1-checked,radio/LOGO.img,880576b3dab4ceae4d1aab9e257894cef27156f4)
$(call add-radio-file-sha1-checked,radio/abl.img,92e584fcf854ed182bcc47ce46b85d68963496d1)
$(call add-radio-file-sha1-checked,radio/aop.img,5832ac8b54cdb18a820ec11d2c937e55119905fc)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,452aa46a5ef265f8f64d1a36f355b67b39ffe4ab)
$(call add-radio-file-sha1-checked,radio/cmnlib.img,a24386c07f624434a7f1948ff7abb6a88ef9c387)
$(call add-radio-file-sha1-checked,radio/cmnlib64.img,c58de0d43010ea448df3251208638a84ff6ddd8b)
$(call add-radio-file-sha1-checked,radio/devcfg.img,7a3860ba8620020d8f24709787387eac913a403a)
$(call add-radio-file-sha1-checked,radio/dsp.img,f77d6b323732185b0514b381ee0c2b872c4cc863)
$(call add-radio-file-sha1-checked,radio/fw_4j1ed.img,ba245847edba65ffa56af879500e4bf833c3c3ca)
$(call add-radio-file-sha1-checked,radio/fw_4u1ea.img,496e61520c33648f7f9915a383256509d39ee931)
$(call add-radio-file-sha1-checked,radio/hyp.img,2f5cbc1959d33a6e0f7bf75d278ab2415c9642eb)
$(call add-radio-file-sha1-checked,radio/keymaster.img,84fb27ff6ab3d5301e0fbfc0a04a26efc8a420d9)
$(call add-radio-file-sha1-checked,radio/modem.img,aefce4366faf0903492d5fa0d3bea436d48c7c43)
$(call add-radio-file-sha1-checked,radio/qupfw.img,ba77b5ddf80966fe6f3840eca21ee539df064942)
$(call add-radio-file-sha1-checked,radio/storsec.img,ad387f5e9f594571848c983615afad862795043d)
$(call add-radio-file-sha1-checked,radio/tz.img,7f927c9bfa352dac8ede56f2faac315e1a77295a)
$(call add-radio-file-sha1-checked,radio/xbl.img,60c2dcea0f61a01cab962068dc1cde944e32cabe)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,f1d8308f5857c249b854dceaa8b49f5d17b5eb3b)

endif
